name: PyDrocsid

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install build dependencies
        run: pip install wheel twine
      - name: Build python package
        run: VERSION=$(echo $GITHUB_REF | cut -d/ -f3) python setup.py sdist bdist_wheel
      - name: Upload package to PyPi
        run: twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
